#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #应用配置
  application:
    name: lms-system
  #文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #JPA
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 5
        max-idle: 8
      shutdown-timeout: 100ms