#服务配置
server:
  port: 9001
#spring配置
spring:
  #应用配置
  application:
    name: lms-community
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #JPA
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379